import { Cairo } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "./components/Navbar";
import { UserProvider } from "./context/User";
import UserRouter from "./context/userRouter";
import "./globals.css";
import { ExamProvider } from "./generate-quiz/_context";
import Script from "next/script";
const inter = Cairo({ subsets: ["latin"] });

export const metadata = {
  title: "Exam Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <UserProvider>
          <UserRouter>
            <div>
              <Navbar />
            </div>
            <div className="min-h-screen">
              <ExamProvider>{children}</ExamProvider>
            </div>
          </UserRouter>
        </UserProvider>
        <Script src="https://www.paypal.com/sdk/js?client-id=AWjB7UwBDMbzxjJj19Sv1JL7R1cmmdgTdv-UeIhgE7tOVAn2AUe8UcT8Ju_maA0zGy0C_ccIx9bIVMrd"></Script>
      </body>
    </html>
  );
}
